"""initial schema

Revision ID: 4a14278b1a51
Revises: 
Create Date: 2026-05-16 04:09:33.714502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a14278b1a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index('uq_seasons_only_one_active', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_subject', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_users_oauth_identity')
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'week_number', name='uq_weeks_season_week_number')
    )
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weeks_season_id'), ['season_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('home_abbr', sa.String(length=5), nullable=False),
    sa.Column('away_abbr', sa.String(length=5), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread_home', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('spread_source', sa.String(length=50), nullable=True),
    sa.Column('spread_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('admin_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'external_id', name='uq_games_week_external_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_kickoff'), ['kickoff'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_week_id'), ['week_id'], unique=False)

    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('picked_side', sa.String(length=10), nullable=False),
    sa.Column('spread_at_pick', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("picked_side <> 'push' OR spread_at_pick = trunc(spread_at_pick)", name='ck_picks_push_requires_whole_spread'),
    sa.CheckConstraint("picked_side IN ('home', 'away', 'push')", name='ck_picks_picked_side'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_picks_user_game')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picks_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picks_user_id'))
        batch_op.drop_index(batch_op.f('ix_picks_game_id'))

    op.drop_table('picks')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_week_id'))
        batch_op.drop_index(batch_op.f('ix_games_kickoff'))

    op.drop_table('games')
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weeks_season_id'))

    op.drop_table('weeks')
    op.drop_table('users')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index('uq_seasons_only_one_active', postgresql_where=sa.text('is_active'))

    op.drop_table('seasons')
    # ### end Alembic commands ###
